name: circom-tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Download Circom Binary v2.2.3
        run: |
          wget -qO /home/runner/work/circom https://github.com/iden3/circom/releases/download/v2.2.3/circom-linux-amd64
          chmod +x /home/runner/work/circom
          sudo mv /home/runner/work/circom /bin/circom

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Print Circom version
        run: circom --version

      - name: Install dependencies
        run: cd wallet-unit-poc/circom && yarn

      - name: Compile JWT circuit
        run: cd wallet-unit-poc/circom && yarn compile:jwt

      - name: Compile Show circuit
        run: cd wallet-unit-poc/circom && yarn compile:show

      - name: Run ecdsa-spartan2 end-to-end flow
        run: |
          cd wallet-unit-poc/ecdsa-spartan2
          cargo run --release -- prepare setup --input ../circom/inputs/jwt/default.json
          cargo run --release -- show setup --input ../circom/inputs/show/default.json
          cargo run --release -- generate_shared_blinds
          cargo run --release -- prepare prove --input ../circom/inputs/jwt/default.json
          RUST_LOG=info cargo run --release -- prepare reblind
          RUST_LOG=info cargo run --release -- show prove --input ../circom/inputs/show/default.json
          RUST_LOG=info cargo run --release -- show reblind
          cargo run --release -- prepare verify
          cargo run --release -- show verify

      - name: Run tests
        run: cd wallet-unit-poc/circom && yarn test
